/*==========================================================================
 * DECLARATION OF AI USE
 *---------------------------------
 * Most of this files content was generated by AI in an agentic process
 * and not revised by a human developer.
 * This is because a working implementation was needed quickly, or because
 * the implementation is not particularly difficult in terms of complexity,
 * but rather in terms of scope.
 * It was determined that the implementation is largely functional;
 * however, a future revision is still desired.
 *==========================================================================*/ 

export {};

declare global {
    interface Window {
        rhombus: {
            deepslate: any;
            densityFunctions: Map<string, (obj: any, inputParser: any) => any>;
            visualizers: Map<string, any>;
            React: any;
            FastNoiseLite: any;
            pako: any;
        };
    }
}

const { deepslate, densityFunctions, FastNoiseLite } = window.rhombus;

if (!deepslate.Registry.REGISTRY.has(deepslate.Identifier.parse("lithostitched:fast_noise_config"))) {
    const registry = new deepslate.Registry(deepslate.Identifier.parse("lithostitched:fast_noise_config"), (obj: any) => obj);
    deepslate.Registry.REGISTRY.register(registry.key, registry);
}

// --- 1. Sqrt ---
class LithostitchedSqrt extends deepslate.DensityFunction {
    input: any;
    constructor(input: any) { super(); this.input = input; }
    compute(context: any): number { return Math.sqrt(Math.max(0, this.input.compute(context))); }
    getMax(): number { return Math.sqrt(Math.max(0, ((this.input.range && typeof this.input.range === 'function') ? this.input.range() : deepslate.Interval.ofExact(0)).max)); }
    range(): any { return deepslate.Interval.of(this.getMin(), this.getMax()); }
    getMin(): number { return Math.sqrt(Math.max(0, ((this.input.range && typeof this.input.range === 'function') ? this.input.range() : deepslate.Interval.ofExact(0)).min)); }
    mapChildren(visitor: any): any { return new LithostitchedSqrt(visitor.apply(this.input)); }
}
densityFunctions.set('lithostitched:sqrt', (obj: any, parser: any) => new LithostitchedSqrt(parser(obj.argument)));

// --- 2. Axis ---
class LithostitchedAxis extends deepslate.DensityFunction {
    axis: 'x' | 'y' | 'z';
    constructor(axis: 'x' | 'y' | 'z') { super(); this.axis = axis; }
    compute(context: any): number {
        if (this.axis === 'x') return context.x;
        if (this.axis === 'y') return context.y;
        return context.z;
    }
    range(): any { return deepslate.Interval.of(this.getMin(), this.getMax()); }
    getMin(): number { return this.axis === 'y' ? -4064 : -1e100; }
    getMax(): number { return this.axis === 'y' ? 4064 : 1e100; }
    mapChildren(visitor: any): any { return this; }
}
densityFunctions.set('lithostitched:axis', (obj: any) => new LithostitchedAxis(obj.axis));

// --- 3. Ceil ---
class LithostitchedCeil extends deepslate.DensityFunction {
    input: any;
    constructor(input: any) { super(); this.input = input; }
    compute(context: any): number { return Math.ceil(this.input.compute(context)); }
    getMax(): number { return Math.ceil(((this.input.range && typeof this.input.range === 'function') ? this.input.range() : deepslate.Interval.ofExact(0)).max); }
    range(): any { return deepslate.Interval.of(this.getMin(), this.getMax()); }
    getMin(): number { return Math.ceil(((this.input.range && typeof this.input.range === 'function') ? this.input.range() : deepslate.Interval.ofExact(0)).min); }
    mapChildren(visitor: any): any { return new LithostitchedCeil(visitor.apply(this.input)); }
}
densityFunctions.set('lithostitched:ceil', (obj: any, parser: any) => new LithostitchedCeil(parser(obj.argument)));

// --- 4. Floor ---
class LithostitchedFloor extends deepslate.DensityFunction {
    input: any;
    constructor(input: any) { super(); this.input = input; }
    compute(context: any): number { return Math.floor(this.input.compute(context)); }
    getMax(): number { return Math.floor(((this.input.range && typeof this.input.range === 'function') ? this.input.range() : deepslate.Interval.ofExact(0)).max); }
    range(): any { return deepslate.Interval.of(this.getMin(), this.getMax()); }
    getMin(): number { return Math.floor(((this.input.range && typeof this.input.range === 'function') ? this.input.range() : deepslate.Interval.ofExact(0)).min); }
    mapChildren(visitor: any): any { return new LithostitchedFloor(visitor.apply(this.input)); }
}
densityFunctions.set('lithostitched:floor', (obj: any, parser: any) => new LithostitchedFloor(parser(obj.argument)));

// --- 5. Sin ---
class LithostitchedSin extends deepslate.DensityFunction {
    input: any;
    constructor(input: any) { super(); this.input = input; }
    compute(context: any): number { return Math.sin(this.input.compute(context)); }
    getMax(): number { return 1; }
    range(): any { return deepslate.Interval.of(this.getMin(), this.getMax()); }
    getMin(): number { return -1; }
    mapChildren(visitor: any): any { return new LithostitchedSin(visitor.apply(this.input)); }
}
densityFunctions.set('lithostitched:sin', (obj: any, parser: any) => new LithostitchedSin(parser(obj.argument)));

// --- 6. Cos ---
class LithostitchedCos extends deepslate.DensityFunction {
    input: any;
    constructor(input: any) { super(); this.input = input; }
    compute(context: any): number { return Math.cos(this.input.compute(context)); }
    getMax(): number { return 1; }
    range(): any { return deepslate.Interval.of(this.getMin(), this.getMax()); }
    getMin(): number { return -1; }
    mapChildren(visitor: any): any { return new LithostitchedCos(visitor.apply(this.input)); }
}
densityFunctions.set('lithostitched:cos', (obj: any, parser: any) => new LithostitchedCos(parser(obj.argument)));

// --- 7. Mix ---
class LithostitchedMix extends deepslate.DensityFunction {
    input: any; arg1: any; arg2: any;
    constructor(input: any, arg1: any, arg2: any) { super(); this.input = input; this.arg1 = arg1; this.arg2 = arg2; }
    compute(context: any): number {
        const i = this.input.compute(context);
        if (i <= 0) return this.arg1.compute(context);
        if (i >= 1) return this.arg2.compute(context);
        return this.arg1.compute(context) * (1 - i) + this.arg2.compute(context) * i;
    }
    range(): any { return deepslate.Interval.of(this.getMin(), this.getMax()); }
    getMin(): number { return Math.min(((this.arg1.range && typeof this.arg1.range === 'function') ? this.arg1.range() : deepslate.Interval.ofExact(0)).min, ((this.arg2.range && typeof this.arg2.range === 'function') ? this.arg2.range() : deepslate.Interval.ofExact(0)).min); }
    getMax(): number { return Math.max(((this.arg1.range && typeof this.arg1.range === 'function') ? this.arg1.range() : deepslate.Interval.ofExact(0)).max, ((this.arg2.range && typeof this.arg2.range === 'function') ? this.arg2.range() : deepslate.Interval.ofExact(0)).max); }
    mapChildren(visitor: any): any { return new LithostitchedMix(visitor.apply(this.input), visitor.apply(this.arg1), visitor.apply(this.arg2)); }
}
densityFunctions.set('lithostitched:mix', (obj: any, parser: any) => new LithostitchedMix(parser(obj.input), parser(obj.argument1), parser(obj.argument2)));

// --- 8. Select ---
class LithostitchedSelect extends deepslate.DensityFunction {
    input: any; fallback: any; selections: any[]; min: number; max: number;
    constructor(input: any, fallback: any, selections: any[]) {
        super(); this.input = input; this.fallback = fallback; this.selections = selections;
        let curMin = ((fallback.range && typeof fallback.range === 'function') ? fallback.range() : deepslate.Interval.ofExact(0)).min;
        let curMax = ((fallback.range && typeof fallback.range === 'function') ? fallback.range() : deepslate.Interval.ofExact(0)).max;
        for (const s of selections) {
            curMin = Math.min(curMin, ((s.function.range && typeof s.function.range === 'function') ? s.function.range() : deepslate.Interval.ofExact(0)).min);
            curMax = Math.max(curMax, ((s.function.range && typeof s.function.range === 'function') ? s.function.range() : deepslate.Interval.ofExact(0)).max);
        }
        this.min = curMin;
        this.max = curMax;
    }
    compute(context: any): number {
        const val = this.input.compute(context);
        for (const sel of this.selections) {
            const minR = sel.range[0];
            const maxR = sel.range[1];
            if (val >= minR && val <= maxR) return sel.function.compute(context);
        }
        return this.fallback.compute(context);
    }
    range(): any { return deepslate.Interval.of(this.getMin(), this.getMax()); }
    getMin(): number { return this.min; }
    getMax(): number { return this.max; }
    mapChildren(visitor: any): any {
        return new LithostitchedSelect(
            visitor.apply(this.input),
            visitor.apply(this.fallback),
            this.selections.map((s: any) => ({ range: s.range, function: visitor.apply(s.function) }))
        );
    }
}
densityFunctions.set('lithostitched:select', (obj: any, parser: any) => {
    const data = obj.select || obj;
    const selections = (data.selections || []).map((s: any) => {
        let range = s.range;
        if (!Array.isArray(range)) range = [range, range];
        return { range, function: parser(s.function) };
    });
    return new LithostitchedSelect(parser(data.input), parser(data.fallback), selections);
});

// --- 9. Shift ---
class LithostitchedShift extends deepslate.DensityFunction {
    input: any; shiftX: any; shiftY: any; shiftZ: any;
    constructor(input: any, shiftX: any, shiftY: any, shiftZ: any) {
        super(); this.input = input; this.shiftX = shiftX; this.shiftY = shiftY; this.shiftZ = shiftZ;
    }
    compute(context: any): number {
        const x = context.x + this.shiftX.compute(context);
        const y = context.y + this.shiftY.compute(context);
        const z = context.z + this.shiftZ.compute(context);
        return this.input.compute({ x, y, z });
    }
    range(): any { return deepslate.Interval.of(this.getMin(), this.getMax()); }
    getMin(): number { return ((this.input.range && typeof this.input.range === 'function') ? this.input.range() : deepslate.Interval.ofExact(0)).min; }
    getMax(): number { return ((this.input.range && typeof this.input.range === 'function') ? this.input.range() : deepslate.Interval.ofExact(0)).max; }
    mapChildren(visitor: any): any { return new LithostitchedShift(visitor.apply(this.input), visitor.apply(this.shiftX), visitor.apply(this.shiftY), visitor.apply(this.shiftZ)); }
}
densityFunctions.set('lithostitched:shift', (obj: any, parser: any) => new LithostitchedShift(parser(obj.input), parser(obj.shift_x), parser(obj.shift_y), parser(obj.shift_z)));

// --- 10. Markers ---
class LithostitchedMarker extends deepslate.DensityFunction {
    constructor() { super(); }
    compute(context: any): number { return 0; }
    range(): any { return deepslate.Interval.of(this.getMin(), this.getMax()); }
    getMin(): number { return 0; }
    getMax(): number { return 0; }
    mapChildren(visitor: any): any { return this; }
}
densityFunctions.set('lithostitched:original_marker', () => new LithostitchedMarker());
densityFunctions.set('lithostitched:wrapped_marker', () => new LithostitchedMarker());

// --- 11. FastNoise ---
class LithostitchedFastNoise extends deepslate.DensityFunction {
    configHolder: any;
    xzScale: number;
    yScale: number;
    shiftX: any;
    shiftY: any;
    shiftZ: any;
    fnl: any;
    initializedConfig: any = null;

    constructor(configHolder: any, xzScale: number, yScale: number, shiftX: any, shiftY: any, shiftZ: any) {
        super();
        this.configHolder = configHolder;
        this.xzScale = xzScale;
        this.yScale = yScale;
        this.shiftX = shiftX;
        this.shiftY = shiftY;
        this.shiftZ = shiftZ;
        
        this.fnl = new FastNoiseLite();
    }

    applyConfig(configData: any) {
        const type = configData.type?.split(':').pop();
        this.fnl.SetFrequency(configData.frequency ?? 0.02);
        if (configData.salt !== undefined) {
            this.fnl.SetSeed(configData.salt);
        }

        if (type === 'cellular') {
            this.fnl.SetNoiseType(FastNoiseLite.NoiseType.Cellular);
            if (configData.distance_function) {
                const df = {
                    'euclidean': FastNoiseLite.CellularDistanceFunction.Euclidean,
                    'euclidean_squared': FastNoiseLite.CellularDistanceFunction.EuclideanSq,
                    'manhattan': FastNoiseLite.CellularDistanceFunction.Manhattan,
                    'hybrid': FastNoiseLite.CellularDistanceFunction.Hybrid
                }[configData.distance_function as string];
                if (df) this.fnl.SetCellularDistanceFunction(df);
            }
            if (configData.return_type) {
                const rt = {
                    'cell_value': FastNoiseLite.CellularReturnType.CellValue,
                    'distance': FastNoiseLite.CellularReturnType.Distance,
                    'distance_2': FastNoiseLite.CellularReturnType.Distance2,
                    'distance_2_add': FastNoiseLite.CellularReturnType.Distance2Add,
                    'distance_2_sub': FastNoiseLite.CellularReturnType.Distance2Sub,
                    'distance_2_mul': FastNoiseLite.CellularReturnType.Distance2Mul,
                    'distance_2_div': FastNoiseLite.CellularReturnType.Distance2Div
                }[configData.return_type as string];
                if (rt) this.fnl.SetCellularReturnType(rt);
            }
            if (configData.jitter !== undefined) {
                this.fnl.SetCellularJitter(configData.jitter);
            }
        } else if (type === 'perlin') {
            this.fnl.SetNoiseType(FastNoiseLite.NoiseType.Perlin);
        } else if (type === 'simplex') {
            this.fnl.SetNoiseType(FastNoiseLite.NoiseType.OpenSimplex2S);
            if (configData.fractal_type) {
                const ft = {
                    'none': FastNoiseLite.FractalType.None,
                    'fbm': FastNoiseLite.FractalType.FBm,
                    'ridged': FastNoiseLite.FractalType.Ridged,
                    'ping_pong': FastNoiseLite.FractalType.PingPong,
                    'domain_warp_progressive': FastNoiseLite.FractalType.DomainWarpProgressive,
                    'domain_warp_independent': FastNoiseLite.FractalType.DomainWarpIndependent
                }[configData.fractal_type as string];
                if (ft) this.fnl.SetFractalType(ft);
            } else {
                this.fnl.SetFractalType(FastNoiseLite.FractalType.None);
            }
            if (configData.octaves !== undefined) this.fnl.SetFractalOctaves(configData.octaves);
            if (configData.lacunarity !== undefined) this.fnl.SetFractalLacunarity(configData.lacunarity);
            if (configData.gain !== undefined) this.fnl.SetFractalGain(configData.gain);
        }
    }

    compute(context: any): number {
        const configData = this.configHolder.value();
        if (this.initializedConfig !== configData) {
            this.initializedConfig = configData;
            this.applyConfig(configData);
        }

        const x = context.x * this.xzScale + this.shiftX.compute(context);
        const y = context.y * this.yScale + this.shiftY.compute(context);
        const z = context.z * this.xzScale + this.shiftZ.compute(context);
        return this.fnl.GetNoise(x, y, z);
    }
    
    range(): any { return deepslate.Interval.of(this.getMin(), this.getMax()); }
    getMin(): number { return -1; }
    getMax(): number { return 1; }

    mapChildren(visitor: any): any {
        return new LithostitchedFastNoise(
            this.configHolder,
            this.xzScale,
            this.yScale,
            visitor.apply(this.shiftX),
            visitor.apply(this.shiftY),
            visitor.apply(this.shiftZ)
        );
    }
}

densityFunctions.set('lithostitched:fast_noise', (obj: any, parser: any) => {
    const registry = deepslate.Registry.REGISTRY.get(deepslate.Identifier.parse("lithostitched:fast_noise_config"));
    const configHolder = deepslate.Holder.parser(registry, (o: any) => o)(obj.config);
    
    return new LithostitchedFastNoise(
        configHolder,
        obj.xz_scale ?? 1.0,
        obj.y_scale ?? 1.0,
        obj.shift_x ? parser(obj.shift_x) : new deepslate.DensityFunction.Constant(0),
        obj.shift_y ? parser(obj.shift_y) : new deepslate.DensityFunction.Constant(0),
        obj.shift_z ? parser(obj.shift_z) : new deepslate.DensityFunction.Constant(0)
    );
});
