[project]
name = "rhombus"
version = "0.0.1"
description = ""
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE" }
authors = [
  { name = "Annhilati"},
]
dependencies = [
  "beet",
  "typer",
  "rich",
  "deepdiff",
  "numpy",
  "matplotlib",
]

[project.urls]
"Homepage" = "https://github.com/annhilati/rhombus"
"Documentation" = "https://annhilati.github.io/rhombus"
# "Changelog" = ""
"Repository" = "https://github.com/annhilati/rhombus"
"Bug Tracker" = "https://github.com/annhilati/rhombus/issues"
# "Download" = "https://pypi.org/project/rhombus/"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["rhombus*"]

[project.scripts]
rhombus = "rhombus.cli:main"