[project]
name = "rhombus"
version = "0.1.0-dev1"
description = ""
readme = "README.md"
requires-python = ">=3.13"
license = { file = "LICENSE" }
authors = [
  { name = "Annhilati"},
]
dependencies = [
  "beet==0.111.0", # -> pyyaml
  "typer==0.25.1",
  "rich==15.0.0",
  "deepdiff==9.1.0",
  "numpy==2.3.3",
  "matplotlib==3.11.0",
]

[project.urls]
homepage = "https://github.com/annhilati/rhombus"
documentation = "https://annhilati.github.io/rhombus"
# "changelog" = ""
repository = "https://github.com/annhilati/rhombus"
issues = "https://github.com/annhilati/rhombus/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["rhombus*"]

# [project.scripts]
# rhombus = "rhombus.cli:main"