/*==========================================================================
 * DECLARATION OF AI USE
 *---------------------------------
 * Most of this files content was generated by AI in an agentic process
 * and not revised by a human developer.
 * This is because a working implementation was needed quickly, or because
 * the implementation is not particularly difficult in terms of complexity,
 * but rather in terms of scope.
 * It was determined that the implementation is largely functional;
 * however, a future revision is still desired.
 *==========================================================================*/ 

export {};

declare global {
    interface Window {
        rhombus: {
            deepslate: any;
            densityFunctions: Map<string, (obj: any, inputParser: any) => any>;
            visualizers: Map<string, any>;
            React: any;
            FastNoiseLite: any;
            pako: any;
        };
    }
}

const { deepslate, densityFunctions, pako } = window.rhombus;

// Helper Math
function clampedMap(val: number, inMin: number, inMax: number, outMin: number, outMax: number) {
    if (val <= inMin) return outMin;
    if (val >= inMax) return outMax;
    return outMin + (outMax - outMin) * ((val - inMin) / (inMax - inMin));
}

//======// Math Maps //=============================================================//
class MoredfsMapped extends deepslate.DensityFunction {
    input: any;
    func: (v: number) => number;
    constructor(input: any, func: (v: number) => number) {
        super();
        this.input = input;
        this.func = func;
    }
    compute(context: any): number { return this.func(this.input.compute(context)); }
    minValue(): number { return -Infinity; }
    maxValue(): number { return Infinity; }
    mapAll(visitor: any): any { return visitor.map(new MoredfsMapped(this.input.mapAll(visitor), this.func)); }
}

const mathMaps: Record<string, (v: number) => number> = {
    'acos': Math.acos,
    'asin': Math.asin,
    'atan': Math.atan,
    'cbrt': Math.cbrt,
    'ceil': Math.ceil,
    'cos': Math.cos,
    'cosh': Math.cosh,
    'floor': Math.floor,
    'log2': Math.log2,
    'log2_floor': (v: number) => Math.floor(Math.log2(v)),
    'ln': Math.log,
    'negate': (v: number) => -v,
    'round': Math.round,
    'sigmoid': (v: number) => 1 / (1 + Math.exp(-v)),
    'signum': Math.sign,
    'sin': Math.sin,
    'sinh': Math.sinh,
    'sqrt': Math.sqrt,
    'tan': Math.tan,
    'tanh': Math.tanh,
    'resolver': (v: number) => v 
};

for (const [name, func] of Object.entries(mathMaps)) {
    densityFunctions.set(`moredfs:${name}`, (obj: any, parser: any) => new MoredfsMapped(parser(obj.argument), func));
}

class MoredfsClamp extends deepslate.DensityFunction {
    input: any; minVal: number; maxVal: number;
    constructor(input: any, minVal: number, maxVal: number) {
        super(); this.input = input; this.minVal = minVal; this.maxVal = maxVal;
    }
    compute(context: any): number { return Math.max(this.minVal, Math.min(this.maxVal, this.input.compute(context))); }
    minValue(): number { return this.minVal; }
    maxValue(): number { return this.maxVal; }
    mapAll(visitor: any): any { return visitor.map(new MoredfsClamp(this.input.mapAll(visitor), this.minVal, this.maxVal)); }
}
densityFunctions.set('moredfs:clamp', (obj: any, parser: any) => new MoredfsClamp(parser(obj.input), obj.min, obj.max));

//======// Division & Modulo //=============================================================//
class MoredfsDivisionBase extends deepslate.DensityFunction {
    arg1: any; arg2: any; func: (a: number, b: number) => number;
    constructor(arg1: any, arg2: any, func: (a: number, b: number) => number) {
        super(); this.arg1 = arg1; this.arg2 = arg2; this.func = func;
    }
    compute(context: any): number { return this.func(this.arg1.compute(context), this.arg2.compute(context)); }
    minValue(): number { return -Infinity; }
    maxValue(): number { return Infinity; }
    mapAll(visitor: any): any { return visitor.map(new MoredfsDivisionBase(this.arg1.mapAll(visitor), this.arg2.mapAll(visitor), this.func)); }
}

const divMaps: Record<string, (a: number, b: number) => number> = {
    'div': (a, b) => a / b,
    'floor_div': (a, b) => Math.floor(a / b),
    'floor_mod': (a, b) => ((a % b) + b) % b,
    'ieee_rem': (a, b) => a - Math.round(a / b) * b,
    'mod': (a, b) => a % b,
    'remainder': (a, b) => a % b,
};

for (const [name, func] of Object.entries(divMaps)) {
    densityFunctions.set(`moredfs:${name}`, (obj: any, parser: any) => new MoredfsDivisionBase(parser(obj.argument1), parser(obj.argument2), func));
}

class MoredfsReciprocal extends deepslate.DensityFunction {
    input: any;
    constructor(input: any) { super(); this.input = input; }
    compute(context: any): number { return 1.0 / this.input.compute(context); }
    minValue(): number { return -Infinity; }
    maxValue(): number { return Infinity; }
    mapAll(visitor: any): any { return visitor.map(new MoredfsReciprocal(this.input.mapAll(visitor))); }
}
densityFunctions.set('moredfs:reciprocal', (obj: any, parser: any) => new MoredfsReciprocal(parser(obj.denominator)));

//======// Double Arguments //=============================================================//
const doubleMaps: Record<string, (a: number, b: number) => number> = {
    'subtract': (a, b) => a - b,
    'vector_angle': (a, b) => Math.atan2(b, a),
    'power': (a, b) => Math.pow(a, b),
    'log': (a, b) => Math.log(a) / Math.log(b),
};

densityFunctions.set('moredfs:subtract', (obj: any, parser: any) => new MoredfsDivisionBase(parser(obj.argument1), parser(obj.argument2), doubleMaps['subtract']));
densityFunctions.set('moredfs:vector_angle', (obj: any, parser: any) => new MoredfsDivisionBase(parser(obj.argument1), parser(obj.argument2), doubleMaps['vector_angle']));
densityFunctions.set('moredfs:power', (obj: any, parser: any) => new MoredfsDivisionBase(parser(obj.base), parser(obj.exponent), doubleMaps['power']));
densityFunctions.set('moredfs:log', (obj: any, parser: any) => new MoredfsDivisionBase(parser(obj.argument), parser(obj.base), doubleMaps['log']));

class MoredfsDotProduct extends deepslate.DensityFunction {
    arg1: any; arg2: any; stepX: number; stepY: number; stepZ: number;
    constructor(arg1: any, arg2: any, stepX: number, stepY: number, stepZ: number) {
        super(); this.arg1 = arg1; this.arg2 = arg2; this.stepX = stepX; this.stepY = stepY; this.stepZ = stepZ;
    }
    compute(context: any): number {
        return this.arg1.compute(context) * this.arg2.compute(context);
    }
    minValue(): number { return -Infinity; }
    maxValue(): number { return Infinity; }
    mapAll(visitor: any): any { return visitor.map(this); }
}
densityFunctions.set('moredfs:dot_product', (obj: any, parser: any) => new MoredfsDotProduct(parser(obj.argument1), parser(obj.argument2), obj.step_x ?? 1, obj.step_y ?? 1, obj.step_z ?? 1));

//======// Simple / Coord Functions //=============================================================//
class MoredfsCoord extends deepslate.DensityFunction {
    type: string;
    constructor(type: string) { super(); this.type = type; }
    compute(context: any): number {
        if (this.type === 'x') return context.x;
        if (this.type === 'y') return context.y;
        if (this.type === 'z') return context.z;
        if (this.type === 'radius') return Math.sqrt(context.x * context.x + context.z * context.z);
        if (this.type === 'radius_3d') return Math.sqrt(context.x * context.x + context.y * context.y + context.z * context.z);
        if (this.type === 'polar_coords') return Math.atan2(context.z, context.x);
        return 0;
    }
    minValue(): number { return -Infinity; }
    maxValue(): number { return Infinity; }
    mapAll(visitor: any): any { return visitor.map(this); }
}
['x', 'y', 'z', 'radius', 'radius_3d', 'polar_coords'].forEach(type => {
    densityFunctions.set(`moredfs:${type}`, () => new MoredfsCoord(type));
});
//======// Advanced Functions //=============================================================//

class MoredfsDistance extends deepslate.DensityFunction {
    metric: string; p1: any[]; p2: any[];
    constructor(metric: string, p1: any[], p2: any[]) {
        super(); this.metric = metric; this.p1 = p1; this.p2 = p2;
    }
    compute(context: any): number {
        const len = Math.max(this.p1.length, this.p2.length);
        if (len === 1) {
            return Math.abs((this.p2[0]?.compute(context) ?? 0) - (this.p1[0]?.compute(context) ?? 0));
        }
        if (this.metric === 'manhattan') {
            let sum = 0;
            for (let i = 0; i < len; i++) sum += Math.abs((this.p2[i]?.compute(context) ?? 0) - (this.p1[i]?.compute(context) ?? 0));
            return sum;
        }
        if (this.metric === 'euclidean') {
            let sum = 0;
            for (let i = 0; i < len; i++) {
                const diff = (this.p2[i]?.compute(context) ?? 0) - (this.p1[i]?.compute(context) ?? 0);
                sum += diff * diff;
            }
            return Math.sqrt(sum);
        }
        if (this.metric === 'chebyshev') {
            let max = 0;
            for (let i = 0; i < len; i++) {
                const diff = Math.abs((this.p2[i]?.compute(context) ?? 0) - (this.p1[i]?.compute(context) ?? 0));
                if (diff > max) max = diff;
            }
            return max;
        }
        if (this.metric.startsWith('minkowski')) {
            const p = parseFloat(this.metric.split('_')[1] || '1');
            let sum = 0;
            for (let i = 0; i < len; i++) sum += Math.pow(Math.abs((this.p2[i]?.compute(context) ?? 0) - (this.p1[i]?.compute(context) ?? 0)), p);
            return Math.pow(sum, 1.0 / p);
        }
        return 0; // fallback
    }
    minValue(): number { return 0; }
    maxValue(): number { return Infinity; }
    mapAll(visitor: any): any { return visitor.map(this); }
}
densityFunctions.set('moredfs:distance', (obj: any, parser: any) => new MoredfsDistance(
    obj.distance_metric?.type?.replace('moredfs:', '') || 'euclidean',
    (obj.point1 || []).map(parser),
    (obj.point2 || []).map(parser)
));

class MoredfsDerivative extends deepslate.DensityFunction {
    argument: any; compX: any; compY: any; compZ: any;
    constructor(argument: any, compX: any, compY: any, compZ: any) {
        super(); this.argument = argument; this.compX = compX; this.compY = compY; this.compZ = compZ;
    }
    compute(context: any): number {
        let dirX = 0, dirY = 0, dirZ = 0;
        let gradX = 0, gradY = 0, gradZ = 0;
        
        if (this.compX) {
            dirX = this.compX.direction.compute(context);
            const step = this.compX.step;
            gradX = (this.argument.compute({ ...context, x: context.x + step }) - this.argument.compute({ ...context, x: context.x - step })) / (2 * step);
        }
        if (this.compY) {
            dirY = this.compY.direction.compute(context);
            const step = this.compY.step;
            gradY = (this.argument.compute({ ...context, y: context.y + step }) - this.argument.compute({ ...context, y: context.y - step })) / (2 * step);
        }
        if (this.compZ) {
            dirZ = this.compZ.direction.compute(context);
            const step = this.compZ.step;
            gradZ = (this.argument.compute({ ...context, z: context.z + step }) - this.argument.compute({ ...context, z: context.z - step })) / (2 * step);
        }
        
        const mag = Math.sqrt(dirX*dirX + dirY*dirY + dirZ*dirZ) || 1;
        return gradX * (dirX/mag) + gradY * (dirY/mag) + gradZ * (dirZ/mag);
    }
    minValue(): number { return -Infinity; }
    maxValue(): number { return Infinity; }
    mapAll(visitor: any): any { return visitor.map(this); }
}
densityFunctions.set('moredfs:derivative', (obj: any, parser: any) => new MoredfsDerivative(
    parser(obj.argument),
    obj.component_x ? { direction: parser(obj.component_x.direction), step: obj.component_x.step } : null,
    obj.component_y ? { direction: parser(obj.component_y.direction), step: obj.component_y.step } : null,
    obj.component_z ? { direction: parser(obj.component_z.direction), step: obj.component_z.step } : null
));

class MoredfsGradientMagnitude extends deepslate.DensityFunction {
    argument: any; stepX: number; stepY: number; stepZ: number;
    constructor(argument: any, stepX: number, stepY: number, stepZ: number) {
        super(); this.argument = argument; this.stepX = stepX; this.stepY = stepY; this.stepZ = stepZ;
    }
    compute(context: any): number {
        let gradX = 0, gradY = 0, gradZ = 0;
        if (this.stepX) gradX = (this.argument.compute({ ...context, x: context.x + this.stepX }) - this.argument.compute({ ...context, x: context.x - this.stepX })) / (2 * this.stepX);
        if (this.stepY) gradY = (this.argument.compute({ ...context, y: context.y + this.stepY }) - this.argument.compute({ ...context, y: context.y - this.stepY })) / (2 * this.stepY);
        if (this.stepZ) gradZ = (this.argument.compute({ ...context, z: context.z + this.stepZ }) - this.argument.compute({ ...context, z: context.z - this.stepZ })) / (2 * this.stepZ);
        return Math.sqrt(gradX*gradX + gradY*gradY + gradZ*gradZ);
    }
    minValue(): number { return 0; }
    maxValue(): number { return Infinity; }
    mapAll(visitor: any): any { return visitor.map(this); }
}
densityFunctions.set('moredfs:gradient_magnitude', (obj: any, parser: any) => new MoredfsGradientMagnitude(parser(obj.argument), obj.step_x ?? 1, obj.step_y ?? 1, obj.step_z ?? 1));

class MoredfsOrElse extends deepslate.DensityFunction {
    argument: any; fallback: any;
    constructor(argument: any, fallback: any) { super(); this.argument = argument; this.fallback = fallback; }
    compute(context: any): number {
        const val = this.argument.compute(context);
        return (isNaN(val) || !isFinite(val)) ? this.fallback.compute(context) : val; // JS doesn't have an exact equivalent to java Optional here, but typically NaNs or throwing.
    }
    minValue(): number { return Math.min(this.argument.minValue(), this.fallback.minValue()); }
    maxValue(): number { return Math.max(this.argument.maxValue(), this.fallback.maxValue()); }
    mapAll(visitor: any): any { return visitor.map(new MoredfsOrElse(this.argument.mapAll(visitor), this.fallback.mapAll(visitor))); }
}
densityFunctions.set('moredfs:or_else', (obj: any, parser: any) => new MoredfsOrElse(parser(obj.argument), parser(obj.fallback)));

class MoredfsProfiler extends deepslate.DensityFunction {
    argument: any;
    constructor(argument: any) { super(); this.argument = argument; }
    compute(context: any): number { return this.argument.compute(context); }
    minValue(): number { return this.argument.minValue(); }
    maxValue(): number { return this.argument.maxValue(); }
    mapAll(visitor: any): any { return visitor.map(new MoredfsProfiler(this.argument.mapAll(visitor))); }
}
densityFunctions.set('moredfs:profiler', (obj: any, parser: any) => new MoredfsProfiler(parser(obj.argument)));

class MoredfsShift extends deepslate.DensityFunction {
    argument: any; shiftX: any; shiftY: any; shiftZ: any;
    constructor(argument: any, shiftX: any, shiftY: any, shiftZ: any) {
        super(); this.argument = argument; this.shiftX = shiftX; this.shiftY = shiftY; this.shiftZ = shiftZ;
    }
    compute(context: any): number {
        const sx = this.shiftX ? this.shiftX.compute(context) : 0;
        const sy = this.shiftY ? this.shiftY.compute(context) : 0;
        const sz = this.shiftZ ? this.shiftZ.compute(context) : 0;
        return this.argument.compute({ x: context.x + sx, y: context.y + sy, z: context.z + sz });
    }
    minValue(): number { return this.argument.minValue(); }
    maxValue(): number { return this.argument.maxValue(); }
    mapAll(visitor: any): any { return visitor.map(this); }
}
densityFunctions.set('moredfs:shift', (obj: any, parser: any) => new MoredfsShift(parser(obj.argument), parser(obj.shift_x), parser(obj.shift_y), parser(obj.shift_z)));

class MoredfsValueNoise extends deepslate.DensityFunction {
    sizeX: number; sizeY: number; sizeZ: number; interp: string; salt: number;
    constructor(sizeX: number, sizeY: number, sizeZ: number, interp: string, salt: number) {
        super(); this.sizeX = sizeX; this.sizeY = sizeY; this.sizeZ = sizeZ; this.interp = interp; this.salt = salt;
    }
    private hash(x: number, y: number, z: number): number {
        // basic fast hash for grid points
        let h = (x * 3129871) ^ (y * 1161293) ^ (z * 7919) ^ this.salt;
        h = (h ^ (h >> 13)) * 2654435761;
        h = (h ^ (h >> 16));
        return (h >>> 0) / 4294967295.0; // 0 to 1
    }
    compute(context: any): number {
        const px = this.sizeX > 0 ? context.x / this.sizeX : 0;
        const py = this.sizeY > 0 ? context.y / this.sizeY : 0;
        const pz = this.sizeZ > 0 ? context.z / this.sizeZ : 0;

        const x0 = Math.floor(px); const y0 = Math.floor(py); const z0 = Math.floor(pz);
        if (this.interp === 'none') return this.hash(x0, y0, z0);

        let tx = px - x0; let ty = py - y0; let tz = pz - z0;
        if (this.interp === 'smoothstep') {
            tx = tx * tx * (3.0 - 2.0 * tx);
            ty = ty * ty * (3.0 - 2.0 * ty);
            tz = tz * tz * (3.0 - 2.0 * tz);
        }

        const c000 = this.hash(x0, y0, z0);
        const c100 = this.hash(x0 + 1, y0, z0);
        const c010 = this.hash(x0, y0 + 1, z0);
        const c110 = this.hash(x0 + 1, y0 + 1, z0);
        const c001 = this.hash(x0, y0, z0 + 1);
        const c101 = this.hash(x0 + 1, y0, z0 + 1);
        const c011 = this.hash(x0, y0 + 1, z0 + 1);
        const c111 = this.hash(x0 + 1, y0 + 1, z0 + 1);

        const c00 = c000 + tx * (c100 - c000);
        const c10 = c010 + tx * (c110 - c010);
        const c01 = c001 + tx * (c101 - c001);
        const c11 = c011 + tx * (c111 - c011);

        const c0 = c00 + ty * (c10 - c00);
        const c1 = c01 + ty * (c11 - c01);

        return c0 + tz * (c1 - c0);
    }
    minValue(): number { return 0; }
    maxValue(): number { return 1; }
    mapAll(visitor: any): any { return visitor.map(this); }
}
densityFunctions.set('moredfs:value_noise', (obj: any, parser: any) => new MoredfsValueNoise(
    obj.size_x ?? 1, obj.size_y ?? 1, obj.size_z ?? 1,
    obj.interpolation ?? 'none', obj.salt ?? 0
));

class MoredfsImageTessellation extends deepslate.DensityFunction {
    xSize: number; zSize: number; data: Uint8Array | null = null;
    constructor(xSize: number, zSize: number, b64Data: string) {
        super(); this.xSize = xSize; this.zSize = zSize;
        if (pako && b64Data) {
            try {
                const binString = atob(b64Data);
                const bytes = new Uint8Array(binString.length);
                for (let i = 0; i < binString.length; i++) bytes[i] = binString.charCodeAt(i);
                this.data = pako.inflate(bytes);
            } catch (e) {
                console.error("Failed to inflate moredfs image tessellation data:", e);
            }
        }
    }
    compute(context: any): number {
        if (!this.data) return 0;
        let x = context.x % this.xSize; if (x < 0) x += this.xSize;
        let z = context.z % this.zSize; if (z < 0) z += this.zSize;
        const idx = Math.floor(x) + Math.floor(z) * this.xSize;
        if (idx >= 0 && idx < this.data.length) return this.data[idx];
        return 0;
    }
    minValue(): number { return 0; }
    maxValue(): number { return 255; }
    mapAll(visitor: any): any { return visitor.map(this); }
}
densityFunctions.set('moredfs:single_channel_image_tessellation', (obj: any, parser: any) => new MoredfsImageTessellation(obj.x_size, obj.z_size, obj.deflated_frame_data));

class MoredfsGappedSpiral extends deepslate.DensityFunction {
    xSize: number; zSize: number; spacing: number; gridCellArgs: any[]; oobArg: any;
    constructor(xSize: number, zSize: number, spacing: number, gridCellArgs: any[], oobArg: any) {
        super(); this.xSize = xSize; this.zSize = zSize; this.spacing = spacing; this.gridCellArgs = gridCellArgs; this.oobArg = oobArg;
    }
    compute(context: any): number {
        const gridX = Math.floor(context.x / this.xSize);
        const gridZ = Math.floor(context.z / this.zSize);
        if (gridX % this.spacing !== 0 || gridZ % this.spacing !== 0) return this.oobArg.compute(context);
        
        const nx = gridX / this.spacing;
        const nz = gridZ / this.spacing;
        const ring = Math.max(Math.abs(nx), Math.abs(nz));
        
        if (ring === 0) return this.gridCellArgs.length > 0 ? this.gridCellArgs[0].compute(context) : this.oobArg.compute(context);
        
        let index = 1 + 4 * ring * (ring - 1);
        // Determine edge (right, top, left, bottom)
        if (nx === ring && nz !== ring) {
            index += (ring - 1 - nz); // right edge (moving up/North in world coords)
        } else if (nz === -ring) {
            index += (2 * ring) + (ring - 1 - nx); // top edge (moving left/West)
        } else if (nx === -ring) {
            index += (4 * ring) + (nz + ring - 1); // left edge (moving down/South)
        } else {
            index += (6 * ring) + (nx + ring - 1); // bottom edge (moving right/East)
        }
        
        if (index >= 0 && index < this.gridCellArgs.length) return this.gridCellArgs[index].compute(context);
        return this.oobArg.compute(context);
    }
    minValue(): number { return -Infinity; }
    maxValue(): number { return Infinity; }
    mapAll(visitor: any): any { return visitor.map(this); }
}
densityFunctions.set('moredfs:gapped_grid_square_spiral', (obj: any, parser: any) => new MoredfsGappedSpiral(
    obj.x_size, obj.z_size, obj.spacing,
    (obj.grid_cell_args || []).map(parser),
    parser(obj.out_of_bounds_argument)
));

class MoredfsClampedGradient extends deepslate.DensityFunction {
    axis: string; from: number; to: number; fromV: number; toV: number;
    constructor(axis: string, from: number, to: number, fromV: number, toV: number) {
        super(); this.axis = axis; this.from = from; this.to = to; this.fromV = fromV; this.toV = toV;
    }
    compute(context: any): number {
        const val = this.axis === 'x' ? context.x : context.z;
        return clampedMap(val, this.from, this.to, this.fromV, this.toV);
    }
    minValue(): number { return Math.min(this.fromV, this.toV); }
    maxValue(): number { return Math.max(this.fromV, this.toV); }
    mapAll(visitor: any): any { return visitor.map(this); }
}
densityFunctions.set('moredfs:x_clamped_gradient', (obj: any, parser: any) => new MoredfsClampedGradient('x', obj.from_x, obj.to_x, obj.from_value, obj.to_value));
densityFunctions.set('moredfs:z_clamped_gradient', (obj: any, parser: any) => new MoredfsClampedGradient('z', obj.from_z, obj.to_z, obj.from_value, obj.to_value));
