from Rhombus import *
from Rhombus.language.functions import MIN_REASONABLE_VALUE, MAX_REASONABLE_VALUE

def overworld():
    jagged_noise                    = ReferenceNoise('minecraft:jagged')
    cave_layer_noise                = ReferenceNoise('minecraft:cave_layer')
    cave_cheese_noise               = ReferenceNoise('minecraft:cave_cheese')
    cave_entrance_noise             = ReferenceNoise('minecraft:cave_entrance')
    spaghetti_2d_noise              = ReferenceNoise('minecraft:spaghetti_2d')
    spaghetti_2d_elevation          = ReferenceNoise('minecraft:spaghetti_2d_elevation')
    spaghetti_2d_modulator_noise    = ReferenceNoise('minecraft:spaghetti_2d_modulator')
    spaghetti_3d_1_noise            = ReferenceNoise('minecraft:spaghetti_3d_1')
    spaghetti_3d_2_noise            = ReferenceNoise('minecraft:spaghetti_3d_2')
    spaghetti_3d_rarity             = ReferenceNoise('minecraft:spaghetti_3d_rarity')
    spaghetti_3d_thickness          = ReferenceNoise('minecraft:spaghetti_3d_thickness')

    overworld_depth      = ref("minecraft:overworld/depth")
    overworld_jaggedness = ref("minecraft:overworld/jaggedness")
    overworld_caves_spaghetti_2d_thickness_modulator = ref("minecraft:overworld/caves/spaghetti_2d_thickness_modulator")

    overworld_sloped_cheese = add(argument1=mul(argument1=(4.0), argument2=quarter_negative(mul(argument1=add(argument1=overworld_depth, argument2=mul(argument1=overworld_jaggedness, argument2=half_negative(noise(noise=jagged_noise, xz_scale=1500.0, y_scale=0.0)))), argument2=ref('minecraft:overworld/factor')))), argument2=ref('minecraft:overworld/base_3d_noise'))
    caves_entrances = cache_once(min(argument1=add(argument1=add(argument1=(0.37), argument2=noise(noise=cave_entrance_noise, xz_scale=0.75, y_scale=0.5)), argument2=y_clamped_gradient(from_y=(-10.0), to_y=(30.0), from_value=(0.3), to_value=(0.0))), argument2=add(argument1=ref('minecraft:overworld/caves/spaghetti_roughness_function'), argument2=clamp(input=add(argument1=max(argument1=weird_scaled_sampler(rarity_value_mapper='type_1', noise=spaghetti_3d_1_noise, input=cache_once(noise(noise=spaghetti_3d_rarity, xz_scale=2.0, y_scale=1.0))), argument2=weird_scaled_sampler(rarity_value_mapper='type_1', noise=spaghetti_3d_2_noise, input=cache_once(noise(noise=spaghetti_3d_rarity, xz_scale=2.0, y_scale=1.0)))), argument2=add(argument1=(-0.0765), argument2=mul(argument1=(-0.011499999999999996), argument2=noise(noise=spaghetti_3d_thickness, xz_scale=1.0, y_scale=1.0)))), min=(-1.0), max=(1.0)))))
    caves_spaghetti_2d = clamp(input=max(argument1=add(argument1=weird_scaled_sampler(rarity_value_mapper='type_2', noise=spaghetti_2d_noise, input=noise(noise=spaghetti_2d_modulator_noise, xz_scale=2.0, y_scale=1.0)), argument2=mul(argument1=(0.083), argument2=overworld_caves_spaghetti_2d_thickness_modulator))), argument2=cube(add(argument1=abs(add(argument1=add(argument1=(0.0), argument2=mul(argument1=(8.0), argument2=noise(noise=spaghetti_2d_elevation, xz_scale=1.0, y_scale=0.0))), argument2=y_clamped_gradient(from_y=(-64.0), to_y=(320.0), from_value=(8.0), to_value=(-40.0)))), argument2=ref('minecraft:overworld/caves/spaghetti_2d_thickness_modulator'))), min=(-1.0), max=(1.0))

    finaLdestiny = min(argument1=squeeze(mul(argument1=(0.64), argument2=interpolated(blend_density(add(argument1=(0.1171875), argument2=mul(argument1=y_clamped_gradient(from_y=(-64.0), to_y=(-40.0), from_value=(0.0), to_value=(1.0)), argument2=add(argument1=(-0.1171875), argument2=add(argument1=(-0.078125), argument2=mul(argument1=y_clamped_gradient(from_y=(240.0), to_y=(256.0), from_value=(1.0), to_value=(0.0)), argument2=add(argument1=(0.078125), argument2=range_choice(input=ref('minecraft:overworld/sloped_cheese'), min_inclusive=(-1000000.0), max_exclusive=(1.5625), when_in_range=min(argument1=overworld_sloped_cheese), argument2=mul(argument1=(5.0), argument2=ref('minecraft:overworld/caves/entrances'))), when_out_of_range=max(argument1=min(argument1=min(argument1=add(argument1=mul(argument1=(4.0), argument2=square(noise(noise=cave_layer_noise, xz_scale=1.0, y_scale=8.0))), argument2=add(argument1=clamp(input=add(argument1=(0.27), argument2=noise(noise=cave_cheese_noise, xz_scale=1.0, y_scale=0.6666666666666666)), min=(-1.0), max=(1.0)), argument2=clamp(input=add(argument1=(1.5), argument2=mul(argument1=(-0.64), argument2=ref('minecraft:overworld/sloped_cheese'))), min=(0.0), max=(0.5)))), argument2=ref('minecraft:overworld/caves/entrances')), argument2=add(argument1=ref('minecraft:overworld/caves/spaghetti_2d'), argument2=ref('minecraft:overworld/caves/spaghetti_roughness_function'))), argument2=range_choice(input=ref('minecraft:overworld/caves/pillars'), min_inclusive=(-1000000.0), max_exclusive=(0.03), when_in_range=(-1000000.0), when_out_of_range=ref('minecraft:overworld/caves/pillars'))))))))))))), argument2=ref('minecraft:overworld/caves/noodle'))