from rhombus.language import *
from rhombus.language.builtins import MIN_REASONABLE_VALUE, MAX_REASONABLE_VALUE
from rhombus.core.df_types import decode_HOLDER_HELPER_CODEC

def overworld():
    jagged_noise                    = ReferencedNoise('minecraft:jagged')
    cave_layer_noise                = ReferencedNoise('minecraft:cave_layer')
    cave_cheese_noise               = ReferencedNoise('minecraft:cave_cheese')
    cave_entrance_noise             = ReferencedNoise('minecraft:cave_entrance')
    spaghetti_2d_noise              = ReferencedNoise('minecraft:spaghetti_2d')
    spaghetti_2d_elevation          = ReferencedNoise('minecraft:spaghetti_2d_elevation')
    spaghetti_2d_modulator_noise    = ReferencedNoise('minecraft:spaghetti_2d_modulator')
    spaghetti_3d_1_noise            = ReferencedNoise('minecraft:spaghetti_3d_1')
    spaghetti_3d_2_noise            = ReferencedNoise('minecraft:spaghetti_3d_2')
    spaghetti_3d_rarity             = ReferencedNoise('minecraft:spaghetti_3d_rarity')
    spaghetti_3d_thickness          = ReferencedNoise('minecraft:spaghetti_3d_thickness')

    overworld_depth      = ref("minecraft:overworld/depth")
    overworld_jaggedness = ref("minecraft:overworld/jaggedness")
    overworld_caves_spaghetti_2d_thickness_modulator = ref("minecraft:overworld/caves/spaghetti_2d_thickness_modulator")

    overworld_sloped_cheese = add(argument1=mul(argument1=constant(argument=4.0), argument2=quarter_negative(argument=mul(argument1=add(argument1=overworld_depth, argument2=mul(argument1=overworld_jaggedness, argument2=half_negative(argument=noise(noise=jagged_noise, xz_scale=1500.0, y_scale=0.0)))), argument2=Reference(reference='minecraft:overworld/factor')))), argument2=Reference(reference='minecraft:overworld/base_3d_noise'))
    caves_entrances = cache_once(argument=min(argument1=add(argument1=add(argument1=constant(argument=0.37), argument2=noise(noise=cave_entrance_noise, xz_scale=0.75, y_scale=0.5)), argument2=y_clamped_gradient(from_y=constant(argument=-10.0), to_y=constant(argument=30.0), from_value=constant(argument=0.3), to_value=constant(argument=0.0))), argument2=add(argument1=Reference(reference='minecraft:overworld/caves/spaghetti_roughness_function'), argument2=clamp(input=add(argument1=max(argument1=weird_scaled_sampler(rarity_value_mapper='type_1', noise=spaghetti_3d_1_noise, input=cache_once(argument=noise(noise=spaghetti_3d_rarity, xz_scale=2.0, y_scale=1.0))), argument2=weird_scaled_sampler(rarity_value_mapper='type_1', noise=spaghetti_3d_2_noise, input=cache_once(argument=noise(noise=spaghetti_3d_rarity, xz_scale=2.0, y_scale=1.0)))), argument2=add(argument1=constant(argument=-0.0765), argument2=mul(argument1=constant(argument=-0.011499999999999996), argument2=noise(noise=spaghetti_3d_thickness, xz_scale=1.0, y_scale=1.0)))), min=constant(argument=-1.0), max=constant(argument=1.0)))))
    caves_spaghetti_2d = clamp(input=max(argument1=add(argument1=weird_scaled_sampler(rarity_value_mapper='type_2', noise=spaghetti_2d_noise, input=noise(noise=spaghetti_2d_modulator_noise, xz_scale=2.0, y_scale=1.0)), argument2=mul(argument1=constant(argument=0.083), argument2=overworld_caves_spaghetti_2d_thickness_modulator))), argument2=cube(argument=add(argument1=abs(argument=add(argument1=add(argument1=constant(argument=0.0), argument2=mul(argument1=constant(argument=8.0), argument2=noise(noise=spaghetti_2d_elevation, xz_scale=1.0, y_scale=0.0))), argument2=y_clamped_gradient(from_y=constant(argument=-64.0), to_y=constant(argument=320.0), from_value=constant(argument=8.0), to_value=constant(argument=-40.0)))), argument2=Reference(reference='minecraft:overworld/caves/spaghetti_2d_thickness_modulator', default=None)))), min=constant(argument=-1.0), max=constant(argument=1.0))

    finaLdestiny = min(argument1=squeeze(argument=mul(argument1=constant(argument=0.64), argument2=interpolated(argument=blend_density(argument=add(argument1=constant(argument=0.1171875), argument2=mul(argument1=y_clamped_gradient(from_y=constant(argument=-64.0), to_y=constant(argument=-40.0), from_value=constant(argument=0.0), to_value=constant(argument=1.0)), argument2=add(argument1=constant(argument=-0.1171875), argument2=add(argument1=constant(argument=-0.078125), argument2=mul(argument1=y_clamped_gradient(from_y=constant(argument=240.0), to_y=constant(argument=256.0), from_value=constant(argument=1.0), to_value=constant(argument=0.0)), argument2=add(argument1=constant(argument=0.078125), argument2=range_choice(input=Reference(reference='minecraft:overworld/sloped_cheese', default=None), min_inclusive=constant(argument=-1000000.0), max_exclusive=constant(argument=1.5625), when_in_range=min(argument1=overworld_sloped_cheese, default=None), argument2=mul(argument1=constant(argument=5.0), argument2=Reference(reference='minecraft:overworld/caves/entrances', default=None))), when_out_of_range=max(argument1=min(argument1=min(argument1=add(argument1=mul(argument1=constant(argument=4.0), argument2=square(argument=noise(noise=cave_layer_noise, xz_scale=1.0, y_scale=8.0))), argument2=add(argument1=clamp(input=add(argument1=constant(argument=0.27), argument2=noise(noise=cave_cheese_noise, xz_scale=1.0, y_scale=0.6666666666666666)), min=constant(argument=-1.0), max=constant(argument=1.0)), argument2=clamp(input=add(argument1=constant(argument=1.5), argument2=mul(argument1=constant(argument=-0.64), argument2=Reference(reference='minecraft:overworld/sloped_cheese', default=None))), min=constant(argument=0.0), max=constant(argument=0.5)))), argument2=Reference(reference='minecraft:overworld/caves/entrances', default=None)), argument2=add(argument1=Reference(reference='minecraft:overworld/caves/spaghetti_2d', default=None), argument2=Reference(reference='minecraft:overworld/caves/spaghetti_roughness_function', default=None))), argument2=range_choice(input=Reference(reference='minecraft:overworld/caves/pillars', default=None), min_inclusive=constant(argument=-1000000.0), max_exclusive=constant(argument=0.03), when_in_range=constant(argument=-1000000.0), when_out_of_range=Reference(reference='minecraft:overworld/caves/pillars', default=None)))))))))))))), argument2=Reference(reference='minecraft:overworld/caves/noodle', default=None))